name: e2e-and-lighthouse
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
      - run: npm i -D @playwright/test && npx playwright install --with-deps
      - run: npx playwright test
  lh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx -y @lhci/cli autorun --collect.url="https://<tu-gh-pages-url>"
